[workspace]
members = [
    "ckb-lib-secp256k1",
    "tests",
    "contracts/ckb-dynamic-loading-secp256k1",
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
